### ISSUE TITLE
Make pdf-tools integrate with window-layout packages

### ISSUE THREAD

**Issue by YiLiu6240** [politza/pdf-tools#232] opened 2016-10-14 14:08 UTC
I often need to switch eyebrowse spaces to work on different parts of a project,
and when I do so if the same pdf document is opened in different spaces they will all
be refreshed to the last active page.

Is it possible to open different pdf pages in different eyebrowse spaces,
like viewing page 1 in eyebrowse window config 1 and page 20 in eyebrowse
window config 2?

**Comment by politza** [comment] 2016-10-14 15:49
The problem is, that pdf-tools resp. image-mode does not understand that the restored window should be treated as some previously deleted window. It views it as a new window, for which it has no information regarding the page and thus switches to the some page previously seen in some other window.

I.e. this needs to be fixed via eyebrowse.

**Comment by YiLiu6240** [comment] 2016-10-14 20:15
OK, thanks!

**Closed** 2022-08-07 11:55 UTC
Labels: enhancement
