### ISSUE TITLE
Issues with Emacs 27/28

### ISSUE THREAD

**Issue by phikal** [politza/pdf-tools#596] opened 2020-06-26 20:45 UTC
Hi,

I'm testing Emacs 28, and noticed that pdf-tools seems to have issues with it. Until now I noticed:

- Searching slows and down the entire session. If you enter more then 3-4 character, Emacs hangs.
- Scrolling won't show the next page when end is reached, _except_ if the entire page fits in the window (usually after pressing `H`).
- Evaluating `(pdf-tools-install)` takes approximately 2-4 times longer (In one experiment 26.1 took ~0.2 seconds while 28.0 required ~0.7).

I'm not sure if Emacs 27 has been tested yet, but if that hasn't been the case, I can rebuild my local checkout and test that too.

**Comment by phikal** [comment] 2020-08-30 13:10
I've tried pdf-tools with Fedora's Emacs 27 build, and the issues remain.

**Comment by hafid68** [comment] 2020-10-13 09:12
I can confirm the scrolling issue with emacs 27:

> Scrolling won't show the next page when end is reached, except if the entire page fits in the window

**Comment by hafid68** [comment] 2020-10-22 10:57
The mentioned issues are fixed by downgrading to emacs 26. Is there any fix for emacs 27 ?

**Comment by cryoguy** [comment] 2020-12-22 01:34
The issue remains with Emacs 27.1 on Arch Linux.

**Comment by antoine-levitt** [comment] 2021-01-26 16:34
Scrolling issue is https://github.com/politza/pdf-tools/pull/649. I don't have the other two.

**Comment by antoine-levitt** [comment] 2021-01-26 16:37
Sorry it's not https://github.com/politza/pdf-tools/pull/649, I've read too fast. Can't reproduce any of these issues then?

**Closed** 2022-08-07 11:54 UTC
