### ISSUE TITLE
"Forgets" annotations

### ISSUE THREAD

**Issue by jabranham** [politza/pdf-tools#205] opened 2016-04-21 16:40 UTC
I am using the latest MELPA build of pdf-tools. When writing text annotations, pdf-tools will "forget" anything past the fourth annotation I add. It just the oldest annotation and adds the new one.

**Comment by billbrod** [comment] 2016-12-06 21:02
I'm having this problem too. Any solution? It's really frustrating.

**Comment by politza** [comment] 2016-12-06 21:45
Is there a recipe producing this behaviour, because I'm unable to do so ?

**Comment by billbrod** [comment] 2016-12-06 22:26
I get this happening (or a similar version, where it seems like pdf-tools has two versions of the file, each with a different subset of annotations, that it switches rapidly every so often, mostly when I save) on an almost blank install; this is all that's in my `.emacs.d/init.el`:

```
(add-to-list 'load-path "~/.emacs.d/el-get/el-get")

(unless (require 'el-get nil 'noerror)
  (with-current-buffer
      (url-retrieve-synchronously
       "https://raw.githubusercontent.com/dimitri/el-get/master/el-get-install.el")
    (goto-char (point-max))
    (eval-print-last-sexp)))

(add-to-list 'el-get-recipe-path "~/.emacs.d/el-get-user/recipes")

(setq my:el-get-packages
      '(pdf-tools))

(el-get 'sync my:el-get-packages)

(pdf-tools-install)
```

I'm on Ubuntu 16.04 LTS and the poppler I'm using is what was installed by defalt on my system, with `libpoppler-dev`, `libpoppler-glib-dev`, `libpoppler-glib8`, `libpoppler-private-dev`, `libpoppler-qt4-4`, `libpoppler58`, and `poppler-utils` all version `0.41.0-0ubuntu1.1`, and `poppler-data` version `0.4.7-7`.

My emacs is version 24.5.1, which I installed from source.

**Comment by politza** [comment] 2016-12-06 23:16
I had something more specific in mind.  Some code I can run in order to experience this behaviour.  I guess its not so easy to reproduce it.

**Comment by billbrod** [comment] 2016-12-06 23:31
Unfortunately not, it basically happens with every pdf I've opened recently and with that minimal setup. I don't have any code to recreate it, because it requires annotating the pdfs. (I've also checked in other pdf editors: they can create annotations without problems (and pdf-tools doesn't destroy those annotations) and they see the same version as I do in emacs, so it's not a displayissue).

Weirdly, it just started happening randomly about 2 weeks ago or so. I haven't been annotating pdfs regularly, so I can't be more specific; the first time I noticed was on Nov 17. I don't think I had updated anything in my emacs around that time, but it's very possible I updated some system libraries using `apt`.

**Comment by politza** [comment] 2016-12-06 23:55
Well, I should have said "some steps I can execute" instead of asking for code to run.  

Is there always a saving of the buffer involved ?

**Comment by politza** [comment] 2016-12-07 00:44
1ab169befeb54db78e94f4ee672966a7bf8aae2a

I hope this fixes it.

**Comment by billbrod** [comment] 2016-12-07 02:44
That appears to have done it, thanks! This is a great package, I'm glad I can keep using it to annotate my pdfs.

**Closed** 2017-08-09 17:49 UTC
