### ISSUE TITLE
Compatibility with M1 Apple silicon

### ISSUE THREAD

**Issue by cilia** [politza/pdf-tools#652] opened 2021-01-28 05:39 UTC
Just tried building this on a M1 Macbook Air (Big Sur 11.1), and got the following errors:

```
---------------------------
 Configuring and compiling
---------------------------
./configure -q --bindir=/Users/cyan/.emacs.d/elpa/pdf-tools-20200512.1524/ && make -s

Is case-sensitive searching enabled ?     yes
Is modifying text annotations enabled ?   yes
Is modifying markup annotations enabled ? yes

ld: warning: ignoring file /opt/homebrew/Cellar/glib/2.66.4_1/lib/libglib-2.0.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /opt/homebrew/Cellar/poppler/21.01.0/lib/libpoppler-glib.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /opt/homebrew/opt/gettext/lib/libintl.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /opt/homebrew/Cellar/glib/2.66.4_1/lib/libgobject-2.0.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /opt/homebrew/Cellar/cairo/1.16.0_4/lib/libcairo.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /opt/homebrew/Cellar/libpng/1.6.37/lib/libpng16.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /opt/homebrew/Cellar/poppler/21.01.0/lib/libpoppler.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
Undefined symbols for architecture x86_64:
  "Annot::setAppearanceState(char const*)", referenced from:
      _xpoppler_annot_set_rectangle in epdfinfo-poppler-hack.o
  "Annot::setRect(double, double, double, double)", referenced from:
      _xpoppler_annot_set_rectangle in epdfinfo-poppler-hack.o
  "_cairo_arc", referenced from:
      _cmd_renderpage in epdfinfo-epdfinfo.o
  "_cairo_close_path", referenced from:
      _cmd_renderpage in epdfinfo-epdfinfo.o
  "_cairo_create", referenced from:
      _cmd_renderpage in epdfinfo-epdfinfo.o
      _image_render_page in epdfinfo-epdfinfo.o
  "_cairo_destroy", referenced from:
      _cmd_renderpage in epdfinfo-epdfinfo.o
      _image_render_page in epdfinfo-epdfinfo.o
  "_cairo_fill_preserve", referenced from:
      _cmd_renderpage in epdfinfo-epdfinfo.o
  "_cairo_image_surface_create", referenced from:
      _cmd_renderpage in epdfinfo-epdfinfo.o
      _image_render_page in epdfinfo-epdfinfo.o
  "_cairo_image_surface_get_data", referenced from:
      _cmd_boundingbox in epdfinfo-epdfinfo.o
      _image_render_page in epdfinfo-epdfinfo.o
      _image_write in epdfinfo-epdfinfo.o
  "_cairo_image_surface_get_height", referenced from:
      _cmd_boundingbox in epdfinfo-epdfinfo.o
      _cmd_renderpage in epdfinfo-epdfinfo.o
      _image_render_page in epdfinfo-epdfinfo.o
      _image_write in epdfinfo-epdfinfo.o
  "_cairo_image_surface_get_stride", referenced from:
      _image_render_page in epdfinfo-epdfinfo.o
  "_cairo_image_surface_get_width", referenced from:
      _cmd_boundingbox in epdfinfo-epdfinfo.o
      _image_render_page in epdfinfo-epdfinfo.o
      _image_write in epdfinfo-epdfinfo.o
  "_cairo_move_to", referenced from:
      _cmd_renderpage in epdfinfo-epdfinfo.o
  "_cairo_paint", referenced from:
      _cmd_renderpage in epdfinfo-epdfinfo.o
      _image_render_page in epdfinfo-epdfinfo.o
  "_cairo_region_create", referenced from:
      _cmd_search_regexp in epdfinfo-epdfinfo.o
      _annotation_print in epdfinfo-epdfinfo.o
  "_cairo_region_destroy", referenced from:
      _cmd_search_regexp in epdfinfo-epdfinfo.o
      _cmd_getselection in epdfinfo-epdfinfo.o
      _annotation_print in epdfinfo-epdfinfo.o
  "_cairo_region_get_rectangle", referenced from:
      _cmd_getselection in epdfinfo-epdfinfo.o
      _region_print in epdfinfo-epdfinfo.o
  "_cairo_region_num_rectangles", referenced from:
      _cmd_getselection in epdfinfo-epdfinfo.o
      _region_print in epdfinfo-epdfinfo.o
  "_cairo_region_union_rectangle", referenced from:
      _cmd_search_regexp in epdfinfo-epdfinfo.o
      _annotation_print in epdfinfo-epdfinfo.o
  "_cairo_scale", referenced from:
      _cmd_renderpage in epdfinfo-epdfinfo.o
      _image_render_page in epdfinfo-epdfinfo.o
  "_cairo_set_line_width", referenced from:
      _cmd_renderpage in epdfinfo-epdfinfo.o
  "_cairo_set_operator", referenced from:
      _image_render_page in epdfinfo-epdfinfo.o
  "_cairo_set_source_rgb", referenced from:
      _image_render_page in epdfinfo-epdfinfo.o
  "_cairo_set_source_rgba", referenced from:
      _cmd_renderpage in epdfinfo-epdfinfo.o
  "_cairo_set_source_surface", referenced from:
      _cmd_renderpage in epdfinfo-epdfinfo.o
  "_cairo_status", referenced from:
      _cmd_renderpage in epdfinfo-epdfinfo.o
      _image_render_page in epdfinfo-epdfinfo.o
  "_cairo_stroke", referenced from:
      _cmd_renderpage in epdfinfo-epdfinfo.o
  "_cairo_surface_destroy", referenced from:
      _cmd_boundingbox in epdfinfo-epdfinfo.o
      _cmd_renderpage in epdfinfo-epdfinfo.o
      _image_render_page in epdfinfo-epdfinfo.o
  "_cairo_surface_flush", referenced from:
      _image_write in epdfinfo-epdfinfo.o
  "_cairo_surface_status", referenced from:
      _cmd_boundingbox in epdfinfo-epdfinfo.o
      _cmd_renderpage in epdfinfo-epdfinfo.o
      _image_render_page in epdfinfo-epdfinfo.o
      _image_write in epdfinfo-epdfinfo.o
  "_cairo_translate", referenced from:
      _image_render_page in epdfinfo-epdfinfo.o
  "_g_array_append_vals", referenced from:
      _cmd_addannot in epdfinfo-epdfinfo.o
  "_g_array_new", referenced from:
      _cmd_addannot in epdfinfo-epdfinfo.o
  "_g_array_unref", referenced from:
      _cmd_addannot in epdfinfo-epdfinfo.o
      _annotation_print in epdfinfo-epdfinfo.o
  "_g_ascii_strtod", referenced from:
      _parse_rectangle in epdfinfo-epdfinfo.o
  "_g_convert", referenced from:
      __xpoppler_goo_string_to_utf8 in epdfinfo-poppler-hack.o
  "_g_error_free", referenced from:
      _cmd_open in epdfinfo-epdfinfo.o
      _cmd_search_regexp in epdfinfo-epdfinfo.o
      _cmd_save in epdfinfo-epdfinfo.o
      _command_arg_parse_arg in epdfinfo-epdfinfo.o
  "_g_filename_to_uri", referenced from:
      _cmd_save in epdfinfo-epdfinfo.o
      _document_open in epdfinfo-epdfinfo.o
  "_g_free", referenced from:
      _main in epdfinfo-epdfinfo.o
      _cmd_setoptions in epdfinfo-epdfinfo.o
      _cmd_search_string in epdfinfo-epdfinfo.o
      _cmd_search_regexp in epdfinfo-epdfinfo.o
      _cmd_metadata in epdfinfo-epdfinfo.o
      _cmd_gettext in epdfinfo-epdfinfo.o
      _cmd_charlayout in epdfinfo-epdfinfo.o
      ...
  "_g_hash_table_destroy", referenced from:
      _free_document in epdfinfo-epdfinfo.o
  "_g_hash_table_insert", referenced from:
      _cmd_addannot in epdfinfo-epdfinfo.o
      _document_open in epdfinfo-epdfinfo.o
      _annoation_get_for_page in epdfinfo-epdfinfo.o
  "_g_hash_table_iter_init", referenced from:
      _cmd_closeall in epdfinfo-epdfinfo.o
  "_g_hash_table_iter_next", referenced from:
      _cmd_closeall in epdfinfo-epdfinfo.o
  "_g_hash_table_iter_remove", referenced from:
      _cmd_closeall in epdfinfo-epdfinfo.o
  "_g_hash_table_lookup", referenced from:
      _cmd_close in epdfinfo-epdfinfo.o
      _cmd_getannot in epdfinfo-epdfinfo.o
      _cmd_addannot in epdfinfo-epdfinfo.o
      _cmd_delannot in epdfinfo-epdfinfo.o
      _cmd_editannot in epdfinfo-epdfinfo.o
      _cmd_getattachment_from_annot in epdfinfo-epdfinfo.o
      _document_open in epdfinfo-epdfinfo.o
      ...
  "_g_hash_table_new", referenced from:
      _main in epdfinfo-epdfinfo.o
      _annoation_get_for_page in epdfinfo-epdfinfo.o
  "_g_hash_table_remove", referenced from:
      _cmd_close in epdfinfo-epdfinfo.o
      _cmd_delannot in epdfinfo-epdfinfo.o
  "_g_list_free", referenced from:
      _cmd_search_string in epdfinfo-epdfinfo.o
      _cmd_addannot in epdfinfo-epdfinfo.o
      _cmd_getattachments in epdfinfo-epdfinfo.o
      _free_document in epdfinfo-epdfinfo.o
      _annoation_get_for_page in epdfinfo-epdfinfo.o
  "_g_list_last", referenced from:
      _cmd_pagelinks in epdfinfo-epdfinfo.o
  "_g_list_length", referenced from:
      _cmd_addannot in epdfinfo-epdfinfo.o
  "_g_list_prepend", referenced from:
      _cmd_addannot in epdfinfo-epdfinfo.o
      _annoation_get_for_page in epdfinfo-epdfinfo.o
  "_g_list_remove", referenced from:
      _cmd_delannot in epdfinfo-epdfinfo.o
  "_g_malloc", referenced from:
      _main in epdfinfo-epdfinfo.o
      _cmd_addannot in epdfinfo-epdfinfo.o
      _annoation_get_for_page in epdfinfo-epdfinfo.o
      _image_write in epdfinfo-epdfinfo.o
  "_g_malloc0", referenced from:
      _main in epdfinfo-epdfinfo.o
      _document_open in epdfinfo-epdfinfo.o
      _annoation_get_for_page in epdfinfo-epdfinfo.o
  "_g_malloc_n", referenced from:
      __xpoppler_goo_string_to_utf8 in epdfinfo-poppler-hack.o
  "_g_match_info_fetch", referenced from:
      _cmd_search_regexp in epdfinfo-epdfinfo.o
  "_g_match_info_fetch_pos", referenced from:
      _cmd_search_regexp in epdfinfo-epdfinfo.o
  "_g_match_info_free", referenced from:
      _cmd_search_regexp in epdfinfo-epdfinfo.o
  "_g_match_info_matches", referenced from:
      _cmd_search_regexp in epdfinfo-epdfinfo.o
  "_g_match_info_next", referenced from:
      _cmd_search_regexp in epdfinfo-epdfinfo.o
  "_g_object_unref", referenced from:
      _cmd_search_string in epdfinfo-epdfinfo.o
      _cmd_search_regexp in epdfinfo-epdfinfo.o
      _cmd_pagelinks in epdfinfo-epdfinfo.o
      _cmd_gettext in epdfinfo-epdfinfo.o
      _cmd_getselection in epdfinfo-epdfinfo.o
      _cmd_pagesize in epdfinfo-epdfinfo.o
      _cmd_boundingbox in epdfinfo-epdfinfo.o
      ...
  "_g_realloc", referenced from:
      _main in epdfinfo-epdfinfo.o
  "_g_regex_match", referenced from:
      _cmd_search_regexp in epdfinfo-epdfinfo.o
  "_g_regex_new", referenced from:
      _cmd_search_regexp in epdfinfo-epdfinfo.o
  "_g_regex_unref", referenced from:
      _cmd_search_regexp in epdfinfo-epdfinfo.o
  "_g_return_if_fail_warning", referenced from:
      _xpoppler_annot_markup_get_created in epdfinfo-poppler-hack.o
  "_g_str_equal", referenced from:
      _main in epdfinfo-epdfinfo.o
      _annoation_get_for_page in epdfinfo-epdfinfo.o
  "_g_str_hash", referenced from:
      _main in epdfinfo-epdfinfo.o
      _annoation_get_for_page in epdfinfo-epdfinfo.o
  "_g_strdup", referenced from:
      _main in epdfinfo-epdfinfo.o
      _document_open in epdfinfo-epdfinfo.o
  "_g_strdup_printf", referenced from:
      _main in epdfinfo-epdfinfo.o
      _cmd_setoptions in epdfinfo-epdfinfo.o
      _cmd_addannot in epdfinfo-epdfinfo.o
      _cmd_editannot in epdfinfo-epdfinfo.o
      _cmd_getattachment_from_annot in epdfinfo-epdfinfo.o
      _cmd_getattachments in epdfinfo-epdfinfo.o
      _cmd_renderpage in epdfinfo-epdfinfo.o
      ...
  "_g_type_check_instance_cast", referenced from:
      _cmd_editannot in epdfinfo-epdfinfo.o
      _cmd_getattachment_from_annot in epdfinfo-epdfinfo.o
      _annotation_print in epdfinfo-epdfinfo.o
      _xpoppler_annot_markup_get_created in epdfinfo-poppler-hack.o
  "_g_type_check_instance_is_a", referenced from:
      _cmd_editannot in epdfinfo-epdfinfo.o
      _cmd_getattachment_from_annot in epdfinfo-epdfinfo.o
      _annotation_print in epdfinfo-epdfinfo.o
      _xpoppler_annot_markup_get_created in epdfinfo-poppler-hack.o
  "_g_ucs4_to_utf8", referenced from:
      __xpoppler_goo_string_to_utf8 in epdfinfo-poppler-hack.o
  "_g_utf8_offset_to_pointer", referenced from:
      _cmd_charlayout in epdfinfo-epdfinfo.o
  "_g_utf8_strlen", referenced from:
      _cmd_search_regexp in epdfinfo-epdfinfo.o
  "_pdfDocEncoding", referenced from:
      __xpoppler_goo_string_to_utf8 in epdfinfo-poppler-hack.o
  "_png_create_info_struct", referenced from:
      _image_write in epdfinfo-epdfinfo.o
  "_png_create_write_struct", referenced from:
      _image_write in epdfinfo-epdfinfo.o
  "_png_destroy_write_struct", referenced from:
      _image_write in epdfinfo-epdfinfo.o
  "_png_init_io", referenced from:
      _image_write in epdfinfo-epdfinfo.o
  "_png_set_IHDR", referenced from:
      _image_write in epdfinfo-epdfinfo.o
  "_png_set_compression_level", referenced from:
      _image_write in epdfinfo-epdfinfo.o
  "_png_set_filter", referenced from:
      _image_write in epdfinfo-epdfinfo.o
  "_png_set_longjmp_fn", referenced from:
      _image_write in epdfinfo-epdfinfo.o
  "_png_write_end", referenced from:
      _image_write in epdfinfo-epdfinfo.o
  "_png_write_info", referenced from:
      _image_write in epdfinfo-epdfinfo.o
  "_png_write_row", referenced from:
      _image_write in epdfinfo-epdfinfo.o
  "_poppler_action_free", referenced from:
      _cmd_outline_walk in epdfinfo-epdfinfo.o
  "_poppler_annot_file_attachment_get_attachment", referenced from:
      _cmd_getattachment_from_annot in epdfinfo-epdfinfo.o
  "_poppler_annot_file_attachment_get_type", referenced from:
      _cmd_getattachment_from_annot in epdfinfo-epdfinfo.o
  "_poppler_annot_get_annot_type", referenced from:
      _annotation_print in epdfinfo-epdfinfo.o
  "_poppler_annot_get_color", referenced from:
      _annotation_print in epdfinfo-epdfinfo.o
  "_poppler_annot_get_contents", referenced from:
      _annotation_print in epdfinfo-epdfinfo.o
  "_poppler_annot_get_flags", referenced from:
      _annotation_print in epdfinfo-epdfinfo.o
  "_poppler_annot_get_modified", referenced from:
      _annotation_print in epdfinfo-epdfinfo.o
  "_poppler_annot_get_page_index", referenced from:
      _cmd_getannot in epdfinfo-epdfinfo.o
      _cmd_delannot in epdfinfo-epdfinfo.o
      _cmd_editannot in epdfinfo-epdfinfo.o
  "_poppler_annot_get_type", referenced from:
      _xpoppler_annot_markup_get_created in epdfinfo-poppler-hack.o
  "_poppler_annot_mapping_free", referenced from:
      _cmd_delannot in epdfinfo-epdfinfo.o
      _free_document in epdfinfo-epdfinfo.o
  "_poppler_annot_mapping_new", referenced from:
      _cmd_addannot in epdfinfo-epdfinfo.o
  "_poppler_annot_markup_get_label", referenced from:
      _annotation_print in epdfinfo-epdfinfo.o
  "_poppler_annot_markup_get_opacity", referenced from:
      _annotation_print in epdfinfo-epdfinfo.o
  "_poppler_annot_markup_get_popup_is_open", referenced from:
      _annotation_print in epdfinfo-epdfinfo.o
  "_poppler_annot_markup_get_popup_rectangle", referenced from:
      _annotation_print in epdfinfo-epdfinfo.o
  "_poppler_annot_markup_get_subject", referenced from:
      _annotation_print in epdfinfo-epdfinfo.o
  "_poppler_annot_markup_get_type", referenced from:
      _cmd_editannot in epdfinfo-epdfinfo.o
      _cmd_getattachment_from_annot in epdfinfo-epdfinfo.o
      _annotation_print in epdfinfo-epdfinfo.o
      _xpoppler_annot_markup_get_created in epdfinfo-poppler-hack.o
  "_poppler_annot_markup_has_popup", referenced from:
      _annotation_print in epdfinfo-epdfinfo.o
  "_poppler_annot_markup_set_label", referenced from:
      _cmd_editannot in epdfinfo-epdfinfo.o
  "_poppler_annot_markup_set_opacity", referenced from:
      _cmd_editannot in epdfinfo-epdfinfo.o
  "_poppler_annot_markup_set_popup", referenced from:
      _cmd_editannot in epdfinfo-epdfinfo.o
  "_poppler_annot_markup_set_popup_is_open", referenced from:
      _cmd_editannot in epdfinfo-epdfinfo.o
  "_poppler_annot_set_color", referenced from:
      _cmd_editannot in epdfinfo-epdfinfo.o
  "_poppler_annot_set_contents", referenced from:
      _cmd_editannot in epdfinfo-epdfinfo.o
  "_poppler_annot_set_flags", referenced from:
      _cmd_editannot in epdfinfo-epdfinfo.o
  "_poppler_annot_text_get_icon", referenced from:
      _annotation_print in epdfinfo-epdfinfo.o
  "_poppler_annot_text_get_is_open", referenced from:
      _annotation_print in epdfinfo-epdfinfo.o
  "_poppler_annot_text_get_state", referenced from:
      _annotation_print in epdfinfo-epdfinfo.o
  "_poppler_annot_text_get_type", referenced from:
      _cmd_editannot in epdfinfo-epdfinfo.o
      _annotation_print in epdfinfo-epdfinfo.o
  "_poppler_annot_text_markup_get_quadrilaterals", referenced from:
      _annotation_print in epdfinfo-epdfinfo.o
  "_poppler_annot_text_markup_get_type", referenced from:
      _annotation_print in epdfinfo-epdfinfo.o
  "_poppler_annot_text_markup_new_highlight", referenced from:
      _cmd_addannot in epdfinfo-epdfinfo.o
  "_poppler_annot_text_markup_new_squiggly", referenced from:
      _cmd_addannot in epdfinfo-epdfinfo.o
  "_poppler_annot_text_markup_new_strikeout", referenced from:
      _cmd_addannot in epdfinfo-epdfinfo.o
  "_poppler_annot_text_markup_new_underline", referenced from:
      _cmd_addannot in epdfinfo-epdfinfo.o
  "_poppler_annot_text_new", referenced from:
      _cmd_addannot in epdfinfo-epdfinfo.o
  "_poppler_annot_text_set_icon", referenced from:
      _cmd_editannot in epdfinfo-epdfinfo.o
  "_poppler_annot_text_set_is_open", referenced from:
      _cmd_editannot in epdfinfo-epdfinfo.o
  "_poppler_attachment_save", referenced from:
      _attachment_print in epdfinfo-epdfinfo.o
  "_poppler_dest_free", referenced from:
      _action_print in epdfinfo-epdfinfo.o
  "_poppler_document_find_dest", referenced from:
      _action_print in epdfinfo-epdfinfo.o
  "_poppler_document_get_attachments", referenced from:
      _cmd_getattachments in epdfinfo-epdfinfo.o
  "_poppler_document_get_author", referenced from:
      _cmd_metadata in epdfinfo-epdfinfo.o
  "_poppler_document_get_creation_date", referenced from:
      _cmd_metadata in epdfinfo-epdfinfo.o
  "_poppler_document_get_creator", referenced from:
      _cmd_metadata in epdfinfo-epdfinfo.o
  "_poppler_document_get_keywords", referenced from:
      _cmd_metadata in epdfinfo-epdfinfo.o
  "_poppler_document_get_modification_date", referenced from:
      _cmd_metadata in epdfinfo-epdfinfo.o
  "_poppler_document_get_n_pages", referenced from:
      _cmd_search_string in epdfinfo-epdfinfo.o
      _cmd_search_regexp in epdfinfo-epdfinfo.o
      _cmd_number_of_pages in epdfinfo-epdfinfo.o
      _cmd_pagelabels in epdfinfo-epdfinfo.o
      _cmd_getannots in epdfinfo-epdfinfo.o
      _free_document in epdfinfo-epdfinfo.o
      _action_print in epdfinfo-epdfinfo.o
      ...
  "_poppler_document_get_page", referenced from:
      _cmd_search_string in epdfinfo-epdfinfo.o
      _cmd_search_regexp in epdfinfo-epdfinfo.o
      _cmd_pagelinks in epdfinfo-epdfinfo.o
      _cmd_gettext in epdfinfo-epdfinfo.o
      _cmd_getselection in epdfinfo-epdfinfo.o
      _cmd_pagesize in epdfinfo-epdfinfo.o
      _cmd_boundingbox in epdfinfo-epdfinfo.o
      ...
  "_poppler_document_get_pdf_version_string", referenced from:
      _cmd_metadata in epdfinfo-epdfinfo.o
  "_poppler_document_get_producer", referenced from:
      _cmd_metadata in epdfinfo-epdfinfo.o
  "_poppler_document_get_subject", referenced from:
      _cmd_metadata in epdfinfo-epdfinfo.o
  "_poppler_document_get_title", referenced from:
      _cmd_metadata in epdfinfo-epdfinfo.o
  "_poppler_document_new_from_file", referenced from:
      _document_open in epdfinfo-epdfinfo.o
  "_poppler_document_save", referenced from:
      _cmd_save in epdfinfo-epdfinfo.o
  "_poppler_index_iter_free", referenced from:
      _cmd_outline in epdfinfo-epdfinfo.o
      _cmd_outline_walk in epdfinfo-epdfinfo.o
  "_poppler_index_iter_get_action", referenced from:
      _cmd_outline_walk in epdfinfo-epdfinfo.o
  "_poppler_index_iter_get_child", referenced from:
      _cmd_outline_walk in epdfinfo-epdfinfo.o
  "_poppler_index_iter_new", referenced from:
      _cmd_outline in epdfinfo-epdfinfo.o
  "_poppler_index_iter_next", referenced from:
      _cmd_outline_walk in epdfinfo-epdfinfo.o
  "_poppler_page_add_annot", referenced from:
      _cmd_addannot in epdfinfo-epdfinfo.o
  "_poppler_page_find_text_with_options", referenced from:
      _cmd_search_string in epdfinfo-epdfinfo.o
  "_poppler_page_free_link_mapping", referenced from:
      _cmd_pagelinks in epdfinfo-epdfinfo.o
  "_poppler_page_get_annot_mapping", referenced from:
      _annoation_get_for_page in epdfinfo-epdfinfo.o
  "_poppler_page_get_crop_box", referenced from:
      _annotation_translate_quadrilateral in epdfinfo-epdfinfo.o
      _cmd_addannot in epdfinfo-epdfinfo.o
      _annotation_print in epdfinfo-epdfinfo.o
  "_poppler_page_get_index", referenced from:
      _annotation_print in epdfinfo-epdfinfo.o
  "_poppler_page_get_label", referenced from:
      _cmd_pagelabels in epdfinfo-epdfinfo.o
  "_poppler_page_get_link_mapping", referenced from:
      _cmd_pagelinks in epdfinfo-epdfinfo.o
  "_poppler_page_get_selected_region", referenced from:
      _cmd_getselection in epdfinfo-epdfinfo.o
  "_poppler_page_get_selected_text", referenced from:
      _cmd_search_string in epdfinfo-epdfinfo.o
      _cmd_search_regexp in epdfinfo-epdfinfo.o
      _cmd_gettext in epdfinfo-epdfinfo.o
  "_poppler_page_get_selection_region", referenced from:
      _cmd_addannot in epdfinfo-epdfinfo.o
  "_poppler_page_get_size", referenced from:
      _cmd_search_string in epdfinfo-epdfinfo.o
      _cmd_search_regexp in epdfinfo-epdfinfo.o
      _cmd_pagelinks in epdfinfo-epdfinfo.o
      _cmd_gettext in epdfinfo-epdfinfo.o
      _cmd_getselection in epdfinfo-epdfinfo.o
      _cmd_pagesize in epdfinfo-epdfinfo.o
      _cmd_boundingbox in epdfinfo-epdfinfo.o
      ...
  "_poppler_page_get_text", referenced from:
      _cmd_search_regexp in epdfinfo-epdfinfo.o
      _cmd_charlayout in epdfinfo-epdfinfo.o
  "_poppler_page_get_text_layout", referenced from:
      _cmd_search_regexp in epdfinfo-epdfinfo.o
      _cmd_charlayout in epdfinfo-epdfinfo.o
  "_poppler_page_remove_annot", referenced from:
      _cmd_delannot in epdfinfo-epdfinfo.o
  "_poppler_page_render", referenced from:
      _image_render_page in epdfinfo-epdfinfo.o
  "_poppler_page_render_for_printing_with_options", referenced from:
      _image_render_page in epdfinfo-epdfinfo.o
  "_poppler_page_render_selection", referenced from:
      _cmd_renderpage in epdfinfo-epdfinfo.o
  "_poppler_rectangle_free", referenced from:
      _cmd_search_string in epdfinfo-epdfinfo.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [epdfinfo] Error 1
make: *** [all] Error 2
===========================
     Build failed.  ;o(   
===========================
Note: maybe try the '-d' option.

Comint exited abnormally with code 1 at Thu Jan 28 13:29:19
```
Emacs and other packages installed via `homebrew` are all M1 native. Any idea how/when we can resolve this for `pdf-tools`

**Comment by wuqui** [comment] 2021-02-11 15:19
I'm facing the same problem. I've tried several things, but have not been able to resolve it. Help would be much appreciated!

**Comment by harritaylor** [comment] 2021-03-16 12:19
@cilia @wuqui I have figured out a temporary solution; install the dependencies in rosetta 2 using intel home-brew.

From what I gather the problem is that emacs runs via rosetta 2 (in my case anyway, you can check by going to activity monitor and taking a sample of the running program). When you install brew for m1, it's built the dependencies for `arm64`, whilst the automake file is expecting `x86_64`. 

1. Run a rosetta 2 terminal (cmd-i click on terminal, check "open in rosetta"), verify you are running intel emulation via `arch` - it should be `i386`
2. Install home-brew to `/usr/local`:
```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```
3. Remove rosetta brew from the terminal for this session 
```
PATH="/usr/local/bin/brew:/usr/bin:/bin:/usr/sbin:/usr/local/bin:/usr/X11/bin"; export PATH;
```
4. Install dependencies and build `pdf-tools`
```
$HOME/.emacs.d/.local/straight/build-27.1/pdf-tools/build/server/autobuild -i $HOME/.emacs.d/.local/straight/build-27.1/pdf-tools/
```

(I'm using `27.1`, so change the path in 4. to wherever the build script is called from)

**Comment by wuqui** [comment] 2021-03-16 17:22
> From what I gather the problem is that emacs runs via rosetta 2 (in my case anyway, you can check by going to activity monitor and taking a sample of the running program). When you install brew for m1, it's built the dependencies for `arm64`, whilst the automake file is expecting `x86_64`.

When I check the Activity Monitor, the `Architecture` for Emacs says `intel` as opposed to `Apple` for other apps. I supposed this means it's not running the native Apple Silicon version, right?

Thanks a lot for sharing your workaround! I have to say, however, that I find this a little bit daunting. I'm not exactly a pro with these things and I don't really want to mess with my homebrew installation since I already had a bunch of issues getting this far. So far, I've tried to stick to ARM homebrew stuff and haven't used Rosetta. At least that's what I thought, maybe Emacs isn't an ARM version after all, judging from the above. I had several problems during the installation of (Doom) Emacs, so I don't even remember which version/distribution ended up working best. I vaguely remember that for a different Emacs distribution (the `d12/frosted` one, I think), `pdf-tools` did work out of the box, but there was some other glitch. 

So would you say I could keep my existing homebrew installation and all my apps as is when I try the steps you recommended above?

**Comment by harritaylor** [comment] 2021-03-16 20:23
>When I check the Activity Monitor, the Architecture for Emacs says intel as opposed to Apple for other apps. I supposed this means it's not running the native Apple Silicon version, right?

correct.

>Thanks a lot for sharing your workaround! I have to say, however, that I find this a little bit daunting. I'm not exactly a pro with these things and I don't really want to mess with my homebrew installation since I already had a bunch of issues getting this far. So far, I've tried to stick to ARM homebrew stuff and haven't used Rosetta. At least that's what I thought, maybe Emacs isn't an ARM version after all, judging from the above. I had several problems during the installation of (Doom) Emacs, so I don't even remember which version/distribution ended up working best. I vaguely remember that for a different Emacs distribution (the d12/frosted one, I think), pdf-tools did work out of the box, but there was some other glitch.

>So would you say I could keep my existing homebrew installation and all my apps as is when I try the steps you recommended above?

Yes, the above step doesn’t replace the native arm homebrew: it’s just there to install the emacs dependencies. As soon as you leave the intel shell, the path you set in 3 will be reset to your regular path, meaning the arm homebrew apps aren’t affected. You can verify by running ‘which brew’: it will be ‘/opt/homebrew/brew’ if it’s back on native arm. 

So far I’ve been using railway cat emacs which has had zero issues for me so far (https://github.com/railwaycat/homebrew-emacsmacport). As far as I can tell you need to build emacs from source for it to be native m1, but I could be wrong. Good luck!

**Comment by wuqui** [comment] 2021-03-18 12:30
Oh boy, @harritaylor, you made me very happy! Your guide worked just perfectly, thanks a million! 🥳 

Just one hint for others maybe: it might be a good idea to duplicate your `Terminal.app` and activate Rosetta and run the above steps on this new copy. This way you have a dedicated Rosetta Terminal app and you don't risk accidentally running stuff via Rosetta. This is also recommended [here](https://www.macrumors.com/2020/11/18/apple-m1-mac-tidbits/), for example.

**Comment by cilia** [comment] 2021-04-10 13:47
@harritaylor Thanks for the workaround. Just to confirm, despite being built in a x86 environment with the Intel `homebrew`, `pdf-tools` package still works well with an Emacs compiled for arm64? And do the `brew` commands in a native arm64 terminal get confused by the ones of the Intel version in any way (I know the `PATH` is set to arm64 version)?

**Comment by ghseeli** [comment] 2021-04-10 17:47
Hi, I am not sure about @harritaylor 's build, but I have emacs compiled as arm64 on my M1 Mac and the steps worked just fine for that. Assuming you have your homebrew setup in the default way for arm, it will be installed in `/opt/homebrew/` versus the x86 version, which should be in `/usr/local`. So, having both versions should not cause any confusion and has not caused any issues for me.

**Closed** 2022-08-07 11:54 UTC
