### ISSUE TITLE
PDF bookmarks marked as invalid

### ISSUE THREAD

**Issue by chiraag-nataraj** [politza/pdf-tools#404] opened 2018-07-23 03:17 UTC
If I open up a PDF in e.g. zathura or mupdf, the PDF bookmarks work perfectly. If I open it in pdf-tools, however, the bookmarks are marked as invalid and other hyperlinks don't work either (within the document). I'll try to upload a MWE in a bit so that you can investigate properly, but just wanted to get the ball rolling.

**Comment by chiraag-nataraj** [comment] 2018-07-23 03:20
Here's a MWE that works perfectly fine in other PDF viewers (both zathura and mupdf recognize the links just fine) but breaks in pdf-tools:
[test.pdf](https://github.com/politza/pdf-tools/files/2217827/test.pdf)

If it matters, I generated this using LaTeX and the bookmarks were generated with hyperref.

**Comment by politza** [comment] 2018-07-23 06:53
The bookmarks in this file work fine with me.

**Comment by chiraag-nataraj** [comment] 2018-07-23 10:44
Hmm. How can I debug this further on my end? Toggling `pdf-tools-toggle-debug` didn't yield any useful info in `*Messages*`.

**Comment by politza** [comment] 2018-07-23 20:17
Enable debugging in Emacs and publish the backtrace.

What poppler version are you using ?

**Comment by chiraag-nataraj** [comment] 2018-07-23 21:48
I have both libpoppler 77 and libpoppler 74, and it looks like other poppler-based tools (like zathura or pdfinfo) are not affected by this. However, those tools seem to be using poppler 77 while epdfinfo is using poppler 74.

I called `pdf-info-outline` directly and got back:
```
(((depth . 1) (type . goto-dest) (title . "A") (page . 0) (top)) ((depth . 1) (type . goto-dest) (title . "B") (page . 0) (top)) ((depth . 1) (type . goto-dest) (title . "C") (page . 0) (top)) ((depth . 1) (type . goto-dest) (title . "D") (page . 0) (top)))
```
which shows that it's getting the wrong page numbers for the outline. This implies `epdfinfo` is the issue. I know I should give you more info, but I'm not entirely sure how to debug efficiently in emacs.

**Comment by politza** [comment] 2018-10-19 17:43
I can't reproduce this and I don't know what else to to, so I'm closing this.

**Closed by politza** 2018-10-19 17:43 UTC
