### ISSUE TITLE
Pdf's produced with Latex-Beamer not viewable

### ISSUE THREAD

**Issue by podczeck** [politza/pdf-tools#552] opened 2020-03-16 13:19 UTC
Hi,

since I updated Poppler to the recent version 0.86.1, I cannot view pdf's produced with the LaTeX-Beamer package in \mode<presentation> (pdf's produced with standard LaTeX, or with the Beamer package but without \mode<presentation> can be viewed as usual). The error message is:

Error during redisplay: (eval (number-to-string (pdf-view-current-page))) signaled (error "The epdfinfo server quit unexpectedly.")

Is this a Poppler bug, or a bug in Pdf-tools or of the Beamer-package, just triggered by the recent Poppler version?

Thanks,

Konrad

**Comment by politza** [comment] 2020-03-16 19:11
Duplicate of #548 ?

**Comment by podczeck** [comment] 2020-03-16 21:04
> Am 16.03.2020 um 20:12 schrieb politza <notifications@github.com>:
> 
> 
> Duplicate of #548 <https://github.com/politza/pdf-tools/issues/548> ?
> 
> 

What speaks against is that #548 refers to Poppler 0.85, a version which didn’t create the problem for me.

**Comment by podczeck** [comment] 2020-03-27 11:51
Following the discussion of bug#548, I did 

brew upgrade

and then

brew upgrade poppler

and after this, everything worked fine again, without the need to recompile pdf-tools. The procedure gave a new version of poppler:  0.86.1_1, which, however is not in the official poppler repo. So the problem I reported was a maybe a bug in homebrew itself?

**Comment by politza** [comment] 2020-03-27 19:01
Looks like it.

**Comment by dinojr** [comment] 2020-04-16 17:51
I'm having the same problem with many pdfs produced by LaTeX, not only the beamer class. I had no problem reading them in pdfview-mode before. I have libpoppler90 (needed by another application) and libpoppler97 installed on my machine but libpoppler.so links to libpoppler.so.97. However, running ldd on epdfinfo gives
```
libpoppler.so.90 => /lib/x86_64-linux-gnu/libpoppler.so.90 (0x00007fc36caab000)
libpoppler.so.97 => /lib/x86_64-linux-gnu/libpoppler.so.97 (0x00007fc36c339000)
```
Is that normal that it's linked with two different versions of libpoppler ?

**Comment by politza** [comment] 2020-04-16 19:25
Try to look if there is a helpful message in the " *epdfinfo*" buffer or
try setting pdf-info-epdfinfo-error-filename.  It's hard to fix this
without knowing what's going on.

**Comment by podczeck** [comment] 2020-04-16 22:04
Let me mention that with poppler 0.87.0 there is no problem for me anymore; pdf-tools showed pdf's produced by any LaTeX class right after installation of poppler 0.87.0. Also, with poppler 0.87.0, I automatically got libpoppler 98.0.0. Maybe try to update. 

Konrad

**Comment by dinojr** [comment] 2020-04-17 08:08
I can't activate debugging : I've set `pdf-info-log` and `pdf-tools-debug` to true and `pdf-info-epdfinfo-error-filename` to `"/tmp/epdfinfo-debug"` and I don't get a `*epdfinfo*` buffer or a `/tmp/epdfinfo-debug` file. What did I miss ?

**Comment by dinojr** [comment] 2020-04-21 08:06
I noticed today, after a restart of Emacs, that the problem is gone: no more crashes of epdfinfo. I'm still using libpoppler97 for epdfinfo.

**Closed** 2022-08-07 11:54 UTC
