### ISSUE TITLE
cannot rebuild epdfinfo

### ISSUE THREAD

**Issue by lomsek14** [politza/pdf-tools#568] opened 2020-05-02 23:00 UTC
Hello, I'm very new on emacs (and programing actually). I downloaded the package pdf-tools via melpa, but when I try to install it `M-x pdf-tools-install`  it displays: `Need to (re)build the epdfinfo program, do it now ? (y or n)`. Then I type 'y' and emacs responds: `pdf-tools-build-server: Wrong type argument: file-directory, "/usr/bin/", target-directory`
How can I remedy that and finally access to pdf-tools?

**Comment by basil-conto** [comment] 2022-04-16 09:48
Is this a duplicate of #508 by any chance?

**Comment by tongjie-chen** [comment] 2022-04-16 14:22
You can step into defun of `pdf-tools-install` and then use `M-x edebug-defun` to track the values and see why the `/usr/bin/` was passed.

**Comment by vedang** [comment] 2022-04-26 02:25
Were you able to solve the problem @lomsek14 ? If so, please close this ticket. If not, please share some information about your setup : 
1. What is your operating system?

**Closed** 2022-08-07 11:54 UTC
